#ifndef compute_ME_C
#define compute_ME_C


#include <TFile.h>
#include <TTree.h>
#include <TString.h>
#include <TCanvas.h>
#include <TH1F.h>
#include <TH2F.h>
#include <TProfile.h>

#include <iostream>
#include <TLegend.h>
#include <TBranch.h>
#include <TClonesArray.h>
#include <TChain.h>
#include <TMath.h>

#include "macro_MG/CPPProcess_uu_to_uuH.cc"
#include "macro_MG/CPPProcess_ud_to_udH.cc"
#include "macro_MG/CPPProcess_uc_to_ucH.cc"
#include "macro_MG/CPPProcess_us_to_usH.cc"
#include "macro_MG/CPPProcess_us_to_dcH.cc"
#include "macro_MG/CPPProcess_uubar_to_uubarH.cc"
#include "macro_MG/CPPProcess_uubar_to_ddbarH.cc"
#include "macro_MG/CPPProcess_udbar_to_udbarH.cc"
#include "macro_MG/CPPProcess_ucbar_to_ucbarH.cc"
#include "macro_MG/CPPProcess_ucbar_to_dsbarH.cc"
#include "macro_MG/CPPProcess_usbar_to_usbarH.cc"

#include "macro_MG/CPPProcess_dd_to_ddH.cc"
#include "macro_MG/CPPProcess_ds_to_dsH.cc"
#include "macro_MG/CPPProcess_ddbar_to_ddbarH.cc"
#include "macro_MG/CPPProcess_ddbar_to_uubarH.cc"
#include "macro_MG/CPPProcess_dsbar_to_dsbarH.cc"
#include "macro_MG/CPPProcess_dsbar_to_ucbarH.cc"



#include <cstdlib>
#include <vector>
#include <string>
#include <iomanip>
#include <iostream>
#include <fstream>
#include <math.h>
#include <time.h>
#include <ct11pdfcpp/ct11pdf.cc>



//Only there to test the ME's on the root files generated by MadGraph
//#include "macro_MG/ExRootClasses.h"
//#include "macro_MG/ExRootTreeReader.h"

//gSystem->Load("/home/llr/cms/strebler/MG5_aMC_v2_2_1/ExRootAnalysis/libExRootAnalysis.so") before compilation in Root





double compute_ultimate_ME_VBF( cteqpdf ct10nn,
				CPPProcess_uu_to_uuH process_uu_to_uuH,
				CPPProcess_ud_to_udH process_ud_to_udH,
				CPPProcess_uc_to_ucH process_uc_to_ucH,
				CPPProcess_us_to_usH process_us_to_usH,
				CPPProcess_us_to_dcH process_us_to_dcH,
				CPPProcess_uubar_to_uubarH process_uubar_to_uubarH,
				CPPProcess_uubar_to_ddbarH process_uubar_to_ddbarH,
				CPPProcess_udbar_to_udbarH process_udbar_to_udbarH,
				CPPProcess_ucbar_to_ucbarH process_ucbar_to_ucbarH,
				CPPProcess_ucbar_to_dsbarH process_ucbar_to_dsbarH,
				CPPProcess_usbar_to_usbarH process_usbar_to_usbarH,
				CPPProcess_dd_to_ddH process_dd_to_ddH,
				//CPPProcess_dc_to_dcH process_dc_to_dcH=process_us_to_usH,
				CPPProcess_ds_to_dsH process_ds_to_dsH,
				//CPPProcess_dubar_to_dubarH process_dubar_to_dubarH=process_udbar_to_udbarH,
				CPPProcess_ddbar_to_ddbarH process_ddbar_to_ddbarH,
				CPPProcess_ddbar_to_uubarH process_ddbar_to_uubarH,
				//CPPProcess_dcbar_to_dcbarH process_dcbar_to_dcbarH=process_usbar->usbar,
				CPPProcess_dsbar_to_dsbarH process_dsbar_to_dsbarH,
				CPPProcess_dsbar_to_ucbarH process_dsbar_to_ucbarH,
				//Cppprocess_cc_to_ccH process_cc_to_ccH=process_uu_to_uuH,
				//CPPProcess_cs_to_csH process_cs_to_csH=process_ud_to_udH,
				//CPPProcess_cubar_to_cubarH process_cubar_to_cubarH=process_ucbar_to_ucbarH,
				//CPPProcess_cubar_to_sdbarH process_cubar_to_sdbarH=process_ucbar_to_dsbarH,
				//CPPProcess_cdbar_to_cdbarH process_cdbar_to_cdbarH=process_dcbar_to_dcbarH,
				//CPPProcess_ccbar_to_ccbarH process_ccbar_to_ccbarH=process_uubar_to_uubarH,
				//CPPProcess_ccbar_to_ssbarH process_ccbar_to_ssbarH=process_uubar_to_ddbarH,
				//CPPProcess_csbar_to_csbarH process_csbar_to_csbarH=process_udbar_to_udbarH,
				//CPPProcess_ss_to_ssH process_ss_to_ssH=process_dd_to_ddH,
				//CPPProcess_subar_to_subarH process_subar_to_subarH=process_usbar_to_usbarH,
				//CPPProcess_sdbar_to_sdbarH process_sdbar_to_sdbarH=process_dsbar_to_dsbarH,
				//CPPProcess_sdbar_to_cubarH process_sdbar_to_cubarH=process_dsbar_to_ucbarH,
				//CPPProcess_scbar_to_scbarH process_scbar_to_scbarH=process_dubar_to_dubarH,
				//CPPProcess_ssbar_to_ssbarH process_ssbar_to_ssbarH=process_ddbar_to_ddbarH,
				//CPPProcess_ssbar_to_ccbarH process_ssbar_to_ccbarH=process_ddbar_to_uubarH,
				//CPPProcess_ubarubar_to_ubarubarH process_ubarubar_to_ubarubarH=process_uu_to_uuH,
				//CPPProcess_ubardbar_to_ubardbarH process_ubardbar_to_ubardbarH=process_ud_to_udH,
				//CPPProcess_ubarcbar_to_ubarcbarH process_ubarcbar_to_ubarcbarH=process_uc_to_ucH,
				//CPPProcess_ubarsbar_to_ubarsbarH process_ubarsbar_to_ubarsbarH=process_us_to_usH,
				//CPPProcess_ubarsbar_to_cbardbarH process_ubarsbar_to_cbardbarH=process_us_to_cdH,
				//CPPProcess_dbardbar_to_dbardbarH process_dbardbar_to_dbardbarH=process_dd_to_ddH,
				//CPPProcess_dbarcbar_to_dbarcbarH process_dbarcbar_to_dbarcbarH=process_dc_to_dcH,
				//CPPProcess_dbarcbar_to_ubarsbarH process_dbarcbar_to_ubarsbarH=process_dc_to_usH,
				//CPPProcess_dbarsbar_to_dbarsbarH process_dbarsbar_to_dbarsbarH=process_ds_to_dsH,
				//CPPProcess_cbarcbar_to_cbarcbarH process_cbarcbar_to_cbarcbarH=process_uu_to_uuH,
				//CPPProcess_cbarsbar_to_cbarsbarH process_cbarsbar_to_cbarsbarH=process_ud_to_udH,
				//CPPProcess_sbarsbar_to_sbarsbarH process_sbarsbar_to_sbarsbarH=process_dd_to_ddH,
				vector<double*> p,
				double E_proton=4000){

  //4 permutations to test
  vector<double*> p0=p;
  vector<double*> p1=p;  
  p1[0]=p[1];
  p1[1]=p[0];
  vector<double*> p2=p;
  p2[2]=p[3];
  p2[3]=p[2];
  vector<double*> p3=p;
  p3[0]=p[1];
  p3[1]=p[0];
  p3[2]=p[3];
  p3[3]=p[2];
  
  double ME2=0;

  double x0=p[0][0]/E_proton;
  double x1=p[1][0]/E_proton;
  double Q=125;


  //PDFs
  double fu0=ct10nn.parton(2,x0,Q);
  double fd0=ct10nn.parton(1,x0,Q);
  double fc0=ct10nn.parton(4,x0,Q);
  double fs0=ct10nn.parton(3,x0,Q);
  double fubar0=ct10nn.parton(-2,x0,Q);
  double fdbar0=ct10nn.parton(-1,x0,Q);
  double fcbar0=ct10nn.parton(-4,x0,Q);
  double fsbar0=ct10nn.parton(-3,x0,Q);

  double fu1=ct10nn.parton(2,x1,Q);
  double fd1=ct10nn.parton(1,x1,Q);
  double fc1=ct10nn.parton(4,x1,Q);
  double fs1=ct10nn.parton(3,x1,Q);
  double fubar1=ct10nn.parton(-2,x1,Q);
  double fdbar1=ct10nn.parton(-1,x1,Q);
  double fcbar1=ct10nn.parton(-4,x1,Q);
  double fsbar1=ct10nn.parton(-3,x1,Q);

  double current_pdf_sum=0;
  double current_ME2=0;



  //uu->uuH, cc->ccH, ubarubar->ubarubarH, cbarcbar->cbarcbarH
  process_uu_to_uuH.setMomenta(p0);
  process_uu_to_uuH.sigmaKin();
  current_ME2=process_uu_to_uuH.getMatrixElements()[0];
  current_pdf_sum=fu0*fu1+fc0*fc1+fubar0*fubar1+fcbar0*fcbar1;
  ME2+=current_pdf_sum*current_ME2;

  //ud->udH, cs->csH, ubardbar->ubardbarH, cbarsbar->cbarsbarH
  process_ud_to_udH.setMomenta(p0);
  process_ud_to_udH.sigmaKin();
  current_ME2=process_ud_to_udH.getMatrixElements()[0];
  current_pdf_sum=fu0*fd1+fc0*fs1+fubar0*fdbar1+fcbar0*fsbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_ud_to_udH.setMomenta(p1);
  process_ud_to_udH.sigmaKin();
  current_ME2=process_ud_to_udH.getMatrixElements()[0];
  current_pdf_sum=fu1*fd0+fc1*fs0+fubar1*fdbar0+fcbar1*fsbar0;
  ME2+=current_pdf_sum*current_ME2;

  process_ud_to_udH.setMomenta(p2);
  process_ud_to_udH.sigmaKin();
  current_ME2=process_ud_to_udH.getMatrixElements()[0];
  current_pdf_sum=fu0*fd1+fc0*fs1+fubar0*fdbar1+fcbar0*fsbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_ud_to_udH.setMomenta(p3);
  process_ud_to_udH.sigmaKin();
  current_ME2=process_ud_to_udH.getMatrixElements()[0];
  current_pdf_sum=fu1*fd0+fc1*fs0+fubar1*fdbar0+fcbar1*fsbar0;
  ME2+=current_pdf_sum*current_ME2;

  //uc->ucH, ubarcbar->ubarcbarH
  process_uc_to_ucH.setMomenta(p0);
  process_uc_to_ucH.sigmaKin();
  current_ME2=process_uc_to_ucH.getMatrixElements()[0];
  current_pdf_sum=fu0*fc1+fubar0*fcbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_uc_to_ucH.setMomenta(p1);
  process_uc_to_ucH.sigmaKin();
  current_ME2=process_uc_to_ucH.getMatrixElements()[0];
  current_pdf_sum=fu1*fc0+fubar1*fcbar0;
  ME2+=current_pdf_sum*current_ME2;

  process_uc_to_ucH.setMomenta(p2);
  process_uc_to_ucH.sigmaKin();
  current_ME2=process_uc_to_ucH.getMatrixElements()[0];
  current_pdf_sum=fu0*fc1+fubar0*fcbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_uc_to_ucH.setMomenta(p3);
  process_uc_to_ucH.sigmaKin();
  current_ME2=process_uc_to_ucH.getMatrixElements()[0];
  current_pdf_sum=fu1*fc0+fubar1*fcbar0;
  ME2+=current_pdf_sum*current_ME2;

  //us->usH, cd->cdH, ubarsbar->ubarsbarH, cbardbar->cbardbarH
  process_us_to_usH.setMomenta(p0);
  process_us_to_usH.sigmaKin();
  current_ME2=process_us_to_usH.getMatrixElements()[0];
  current_pdf_sum=fu0*fs1+fc0*fd1+fubar0*fsbar1+fcbar0*fdbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_us_to_usH.setMomenta(p1);
  process_us_to_usH.sigmaKin();
  current_ME2=process_us_to_usH.getMatrixElements()[0];
  current_pdf_sum=fu1*fs0+fc1*fd0+fubar1*fsbar0+fcbar1*fdbar0;
  ME2+=current_pdf_sum*current_ME2;

  process_us_to_usH.setMomenta(p2);
  process_us_to_usH.sigmaKin();
  current_ME2=process_us_to_usH.getMatrixElements()[0];
  current_pdf_sum=fu0*fs1+fc0*fd1+fubar0*fsbar1+fcbar0*fdbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_us_to_usH.setMomenta(p3);
  process_us_to_usH.sigmaKin();
  current_ME2=process_us_to_usH.getMatrixElements()[0];
  current_pdf_sum=fu1*fs0+fc1*fd0+fubar1*fsbar0+fcbar1*fdbar0;
  ME2+=current_pdf_sum*current_ME2;
  
  //us->cdH, cd->usH, ubarsbar->cbardbarH, cbardbar->ubarsbarH
  process_us_to_dcH.setMomenta(p0);
  process_us_to_dcH.sigmaKin();
  current_ME2=process_us_to_dcH.getMatrixElements()[0];
  current_pdf_sum=fu0*fs1+fc0*fd1+fubar0*fsbar1+fcbar0*fdbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_us_to_dcH.setMomenta(p1);
  process_us_to_dcH.sigmaKin();
  current_ME2=process_us_to_dcH.getMatrixElements()[0];
  current_pdf_sum=fu1*fs0+fc1*fd0+fubar1*fsbar0+fcbar1*fdbar0;
  ME2+=current_pdf_sum*current_ME2;

  process_us_to_dcH.setMomenta(p2);
  process_us_to_dcH.sigmaKin();
  current_ME2=process_us_to_dcH.getMatrixElements()[0];
  current_pdf_sum=fu0*fs1+fc0*fd1+fubar0*fsbar1+fcbar0*fdbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_us_to_dcH.setMomenta(p3);
  process_us_to_dcH.sigmaKin();
  current_ME2=process_us_to_dcH.getMatrixElements()[0];
  current_pdf_sum=fu1*fs0+fc1*fd0+fubar1*fsbar0+fcbar1*fdbar0;
  ME2+=current_pdf_sum*current_ME2;

  //uubar->uubarH, ccbar->ccbarH
  process_uubar_to_uubarH.setMomenta(p0);
  process_uubar_to_uubarH.sigmaKin();
  current_ME2=process_uubar_to_uubarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fubar1+fc0*fcbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_uubar_to_uubarH.setMomenta(p1);
  process_uubar_to_uubarH.sigmaKin();
  current_ME2=process_uubar_to_uubarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fubar0+fc1*fcbar0;
  ME2+=current_pdf_sum*current_ME2;

  process_uubar_to_uubarH.setMomenta(p2);
  process_uubar_to_uubarH.sigmaKin();
  current_ME2=process_uubar_to_uubarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fubar1+fc0*fcbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_uubar_to_uubarH.setMomenta(p3);
  process_uubar_to_uubarH.sigmaKin();
  current_ME2=process_uubar_to_uubarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fubar0+fc1*fcbar0;
  ME2+=current_pdf_sum*current_ME2;

  //uubar->ddbarH, ccbar->ssbarH
  process_uubar_to_ddbarH.setMomenta(p0);
  process_uubar_to_ddbarH.sigmaKin();
  current_ME2=process_uubar_to_ddbarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fubar1+fc0*fcbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_uubar_to_ddbarH.setMomenta(p1);
  process_uubar_to_ddbarH.sigmaKin();
  current_ME2=process_uubar_to_ddbarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fubar0+fc1*fcbar0;
  ME2+=current_pdf_sum*current_ME2;

  process_uubar_to_ddbarH.setMomenta(p2);
  process_uubar_to_ddbarH.sigmaKin();
  current_ME2=process_uubar_to_ddbarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fubar1+fc0*fcbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_uubar_to_ddbarH.setMomenta(p3);
  process_uubar_to_ddbarH.sigmaKin();
  current_ME2=process_uubar_to_ddbarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fubar0+fc1*fcbar0;
  ME2+=current_pdf_sum*current_ME2;


  //udbar->udbarH, csbar->csbarH, ubard->ubardH, cbars->cbarsH,
  process_udbar_to_udbarH.setMomenta(p0);
  process_udbar_to_udbarH.sigmaKin();
  current_ME2=process_udbar_to_udbarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fdbar1+fc0*fsbar1+fubar0*fd1+fcbar0*fs1;
  ME2+=current_pdf_sum*current_ME2;

  process_udbar_to_udbarH.setMomenta(p1);
  process_udbar_to_udbarH.sigmaKin();
  current_ME2=process_udbar_to_udbarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fdbar0+fc1*fsbar0+fubar1*fd0+fcbar1*fs0;
  ME2+=current_pdf_sum*current_ME2;

  process_udbar_to_udbarH.setMomenta(p2);
  process_udbar_to_udbarH.sigmaKin();
  current_ME2=process_udbar_to_udbarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fdbar1+fc0*fsbar1+fubar0*fd1+fcbar0*fs1;
  ME2+=current_pdf_sum*current_ME2;

  process_udbar_to_udbarH.setMomenta(p3);
  process_udbar_to_udbarH.sigmaKin();
  current_ME2=process_udbar_to_udbarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fdbar0+fc1*fsbar0+fubar1*fd0+fcbar1*fs0;
  ME2+=current_pdf_sum*current_ME2;
  
  //ucbar->ucbarH, ubarc->ubarcH
  process_ucbar_to_ucbarH.setMomenta(p0);
  process_ucbar_to_ucbarH.sigmaKin();
  current_ME2=process_ucbar_to_ucbarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fcbar1+fubar0*fc1;
  ME2+=current_pdf_sum*current_ME2;

  process_ucbar_to_ucbarH.setMomenta(p1);
  process_ucbar_to_ucbarH.sigmaKin();
  current_ME2=process_ucbar_to_ucbarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fcbar0+fubar1*fc0;
  ME2+=current_pdf_sum*current_ME2;

  process_ucbar_to_ucbarH.setMomenta(p2);
  process_ucbar_to_ucbarH.sigmaKin();
  current_ME2=process_ucbar_to_ucbarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fcbar1+fubar0*fc1;
  ME2+=current_pdf_sum*current_ME2;

  process_ucbar_to_ucbarH.setMomenta(p3);
  process_ucbar_to_ucbarH.sigmaKin();
  current_ME2=process_ucbar_to_ucbarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fcbar0+fubar1*fc0;
  ME2+=current_pdf_sum*current_ME2;

  //ucbar->dsbarH, ubarc->dbarsH
  process_ucbar_to_dsbarH.setMomenta(p0);
  process_ucbar_to_dsbarH.sigmaKin();
  current_ME2=process_ucbar_to_dsbarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fcbar1+fubar0*fc1;
  ME2+=current_pdf_sum*current_ME2;

  process_ucbar_to_dsbarH.setMomenta(p1);
  process_ucbar_to_dsbarH.sigmaKin();
  current_ME2=process_ucbar_to_dsbarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fcbar0+fubar1*fc0;
  ME2+=current_pdf_sum*current_ME2;

  process_ucbar_to_dsbarH.setMomenta(p2);
  process_ucbar_to_dsbarH.sigmaKin();
  current_ME2=process_ucbar_to_dsbarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fcbar1+fubar0*fc1;
  ME2+=current_pdf_sum*current_ME2;

  process_ucbar_to_dsbarH.setMomenta(p3);
  process_ucbar_to_dsbarH.sigmaKin();
  current_ME2=process_ucbar_to_dsbarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fcbar0+fubar1*fc0;
  ME2+=current_pdf_sum*current_ME2;

  //usbar->usbarH, cdbar->cdbarH, ubars->ubarsH, cbard->cbardH
  process_usbar_to_usbarH.setMomenta(p0);
  process_usbar_to_usbarH.sigmaKin();
  current_ME2=process_usbar_to_usbarH.getMatrixElements()[0];
  current_pdf_sum=fu0*fsbar1+fc0*fdbar1+fubar0*fs1+fcbar0*fd1;
  ME2+=current_pdf_sum*current_ME2;

  process_usbar_to_usbarH.setMomenta(p1);
  process_usbar_to_usbarH.sigmaKin();
  current_ME2=process_usbar_to_usbarH.getMatrixElements()[0];
  current_pdf_sum=fu1*fsbar0+fc1*fdbar0+fubar1*fs0+fcbar1*fd0;
  ME2+=current_pdf_sum*current_ME2;

  //dd->ddH, ss->ssH, dbardbar->dbardbarH, sbarsbar->sbarsbarH
  process_dd_to_ddH.setMomenta(p0);
  process_dd_to_ddH.sigmaKin();
  current_ME2=process_dd_to_ddH.getMatrixElements()[0];
  current_pdf_sum=fd0*fd1+fs0*fs1+fdbar0*fdbar1+fsbar0*fsbar1;
  ME2+=current_pdf_sum*current_ME2;

  //ds->dsH, dbarsbar->dbarsbarH
  process_ds_to_dsH.setMomenta(p0);
  process_ds_to_dsH.sigmaKin();
  current_ME2=process_ds_to_dsH.getMatrixElements()[0];
  current_pdf_sum=fd0*fs1+fdbar0*fsbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_ds_to_dsH.setMomenta(p1);
  process_ds_to_dsH.sigmaKin();
  current_ME2=process_ds_to_dsH.getMatrixElements()[0];
  current_pdf_sum=fd1*fs0+fdbar1*fsbar0;
  ME2+=current_pdf_sum*current_ME2;

  process_ds_to_dsH.setMomenta(p2);
  process_ds_to_dsH.sigmaKin();
  current_ME2=process_ds_to_dsH.getMatrixElements()[0];
  current_pdf_sum=fd0*fs1+fdbar0*fsbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_ds_to_dsH.setMomenta(p3);
  process_ds_to_dsH.sigmaKin();
  current_ME2=process_ds_to_dsH.getMatrixElements()[0];
  current_pdf_sum=fd1*fs0+fdbar1*fsbar0;
  ME2+=current_pdf_sum*current_ME2;
  
  //ddbar->ddbarH, ssbar->ssbarH
  process_ddbar_to_ddbarH.setMomenta(p0);
  process_ddbar_to_ddbarH.sigmaKin();
  current_ME2=process_ddbar_to_ddbarH.getMatrixElements()[0];
  current_pdf_sum=fd0*fdbar1+fs0*fsbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_ddbar_to_ddbarH.setMomenta(p1);
  process_ddbar_to_ddbarH.sigmaKin();
  current_ME2=process_ddbar_to_ddbarH.getMatrixElements()[0];
  current_pdf_sum=fd1*fdbar0+fs1*fsbar0;
  ME2+=current_pdf_sum*current_ME2;

  process_ddbar_to_ddbarH.setMomenta(p2);
  process_ddbar_to_ddbarH.sigmaKin();
  current_ME2=process_ddbar_to_ddbarH.getMatrixElements()[0];
  current_pdf_sum=fd0*fdbar1+fs0*fsbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_ddbar_to_ddbarH.setMomenta(p3);
  process_ddbar_to_ddbarH.sigmaKin();
  current_ME2=process_ddbar_to_ddbarH.getMatrixElements()[0];
  current_pdf_sum=fd1*fdbar0+fs1*fsbar0;
  ME2+=current_pdf_sum*current_ME2;

  //ddbar->uubarH, ssbar->ccbarH
  process_ddbar_to_uubarH.setMomenta(p0);
  process_ddbar_to_uubarH.sigmaKin();
  current_ME2=process_ddbar_to_uubarH.getMatrixElements()[0];
  current_pdf_sum=fd0*fdbar1+fs0*fsbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_ddbar_to_uubarH.setMomenta(p1);
  process_ddbar_to_uubarH.sigmaKin();
  current_ME2=process_ddbar_to_uubarH.getMatrixElements()[0];
  current_pdf_sum=fd1*fdbar0+fs1*fsbar0;
  ME2+=current_pdf_sum*current_ME2;

  process_ddbar_to_uubarH.setMomenta(p2);
  process_ddbar_to_uubarH.sigmaKin();
  current_ME2=process_ddbar_to_uubarH.getMatrixElements()[0];
  current_pdf_sum=fd0*fdbar1+fs0*fsbar1;
  ME2+=current_pdf_sum*current_ME2;

  process_ddbar_to_uubarH.setMomenta(p3);
  process_ddbar_to_uubarH.sigmaKin();
  current_ME2=process_ddbar_to_uubarH.getMatrixElements()[0];
  current_pdf_sum=fd1*fdbar0+fs1*fsbar0;
  ME2+=current_pdf_sum*current_ME2;
  
  //dsbar->dsbarH, dbars->dbarsH
  process_dsbar_to_dsbarH.setMomenta(p0);
  process_dsbar_to_dsbarH.sigmaKin();
  current_ME2=process_dsbar_to_dsbarH.getMatrixElements()[0];
  current_pdf_sum=fd0*fsbar1+fdbar0*fs1;
  ME2+=current_pdf_sum*current_ME2;

  process_dsbar_to_dsbarH.setMomenta(p1);
  process_dsbar_to_dsbarH.sigmaKin();
  current_ME2=process_dsbar_to_dsbarH.getMatrixElements()[0];
  current_pdf_sum=fd1*fsbar0+fdbar1*fs0;
  ME2+=current_pdf_sum*current_ME2;

  process_dsbar_to_dsbarH.setMomenta(p2);
  process_dsbar_to_dsbarH.sigmaKin();
  current_ME2=process_dsbar_to_dsbarH.getMatrixElements()[0];
  current_pdf_sum=fd0*fsbar1+fdbar0*fs1;
  ME2+=current_pdf_sum*current_ME2;

  process_dsbar_to_dsbarH.setMomenta(p3);
  process_dsbar_to_dsbarH.sigmaKin();
  current_ME2=process_dsbar_to_dsbarH.getMatrixElements()[0];
  current_pdf_sum=fd1*fsbar0+fdbar1*fs0;
  ME2+=current_pdf_sum*current_ME2;

  //dsbar->ucbarH, dbars->ubarcH
  process_dsbar_to_ucbarH.setMomenta(p0);
  process_dsbar_to_ucbarH.sigmaKin();
  current_ME2=process_dsbar_to_ucbarH.getMatrixElements()[0];
  current_pdf_sum=fd0*fsbar1+fdbar0*fs1;
  ME2+=current_pdf_sum*current_ME2;

  process_dsbar_to_ucbarH.setMomenta(p1);
  process_dsbar_to_ucbarH.sigmaKin();
  current_ME2=process_dsbar_to_ucbarH.getMatrixElements()[0];
  current_pdf_sum=fd1*fsbar0+fdbar1*fs0;
  ME2+=current_pdf_sum*current_ME2;

  process_dsbar_to_ucbarH.setMomenta(p2);
  process_dsbar_to_ucbarH.sigmaKin();
  current_ME2=process_dsbar_to_ucbarH.getMatrixElements()[0];
  current_pdf_sum=fd0*fsbar1+fdbar0*fs1;
  ME2+=current_pdf_sum*current_ME2;

  process_dsbar_to_ucbarH.setMomenta(p3);
  process_dsbar_to_ucbarH.sigmaKin();
  current_ME2=process_dsbar_to_ucbarH.getMatrixElements()[0];
  current_pdf_sum=fd1*fsbar0+fdbar1*fs0;
  ME2+=current_pdf_sum*current_ME2;
  



  return ME2;
}




 







double compute_ME_VBF_v2( cteqpdf ct10nn,
			  CPPProcess_uu_to_uuH process_uu_to_uuH,
			  CPPProcess_ud_to_udH process_ud_to_udH,
			  CPPProcess_us_to_dcH process_us_to_dcH,
			  vector<double*> p){

  //p0 incoming quark with eta>0
  //p1 incoming quark with eta<0
  //p2 outgoing quark with highest eta
  //p3 outgoing quark with lowest eta

  vector<double*> p_good=p;
  vector<double*> p_bad=p;
  p_bad[2]=p[3];
  p_bad[3]=p[2];
  
  double ME2=0;

  double E_proton=6500;
  double x0=p[0][0]/E_proton;
  double x1=p[1][0]/E_proton;
  double Q=125;

  double fu0=ct10nn.parton(2,x0,Q);
  double fd0=ct10nn.parton(1,x0,Q);
  double fc0=ct10nn.parton(4,x0,Q);
  double fs0=ct10nn.parton(3,x0,Q);
  double fubar0=ct10nn.parton(-2,x0,Q);
  double fdbar0=ct10nn.parton(-1,x0,Q);
  double fcbar0=ct10nn.parton(-4,x0,Q);
  double fsbar0=ct10nn.parton(-3,x0,Q);

  double fu1=ct10nn.parton(2,x1,Q);
  double fd1=ct10nn.parton(1,x1,Q);
  double fc1=ct10nn.parton(4,x1,Q);
  double fs1=ct10nn.parton(3,x1,Q);
  double fubar1=ct10nn.parton(-2,x1,Q);
  double fdbar1=ct10nn.parton(-1,x1,Q);
  double fcbar1=ct10nn.parton(-4,x1,Q);
  double fsbar1=ct10nn.parton(-3,x1,Q);

  double current_pdf_sum=0;
  double current_ME2=0;

  //uu->uuH, dd->ddH, cc->ccH, ss->ssH, ubarubar->ubarubarH, dbardbar->dbardbarH, cbarcbar->cbarcbarH, sbarsbar->sbarsbarH,
  current_pdf_sum=fu0*fu1+fd0*fd1+fc0*fc1+fs0*fs1+fubar0*fubar1+fdbar0*fdbar1+fcbar0*fcbar1+fsbar0*fsbar1;
  process_uu_to_uuH.setMomenta(p_good);
  process_uu_to_uuH.sigmaKin();
  current_ME2=process_uu_to_uuH.getMatrixElements()[0];
  ME2+=current_pdf_sum*current_ME2;

  //ud->udH, cs->csH, ubardbar->ubardbarH, cbarsbar->cbarsbarH
  current_pdf_sum=fu0*fd1+fc0*fs1+fubar0*fdbar1+fcbar0*fsbar1+fu1*fd0+fc1*fs0+fubar1*fdbar0+fcbar1*fsbar0;
  process_ud_to_udH.setMomenta(p_good);
  process_ud_to_udH.sigmaKin();
  current_ME2=process_ud_to_udH.getMatrixElements()[0];
  ME2+=current_pdf_sum*current_ME2;

  process_ud_to_udH.setMomenta(p_bad);
  process_ud_to_udH.sigmaKin();
  current_ME2=process_ud_to_udH.getMatrixElements()[0];
  ME2+=current_pdf_sum*current_ME2;


  //Others: uc->ucH, us->usH, us->cdH, uubar->uubarH, uubar->ddbarH, udbar->udbarH, ucbar->ucbarH, ucbar->dsbarH, usbar->usbarH, dc->dcH, dc->usH, ds->dsH, dubar->dubarH, ddbar->ddbarH, ddbar->uubarH, dcbar->dcbarH, dsbar->dsbarH, dsbar->ucbarH, cubar->cubarH, cubar->sdbarH, cdbar->cdbarH, ccbar->ccbarH, ccbar->ssbarH, csbar->csbarH, subar->subarH, sdbar->sdbarH, sdbar->cubarH, scbar->scbarH, ssbar->ccbarH, ssbar->ssbarH, ubarcbar->ubarcbarH, ubarsbar->ubarsbarH, ubarsbar->cbardbarH, dbarcbar->dbarcbarH, dbarcbar->ubarsbarH, dbarsbar->dbarsbarH
  current_pdf_sum=fu0*fc1+2*fu0*fs1+2*fu0*fubar1+fu0*fdbar1+2*fu0*fcbar1+fu0*fsbar1+2*fd0*fc1+fd0*fs1+fd0*fubar1+2*fd0*fdbar1+fd0*fcbar1+2*fd0*fsbar1+2*fc0*fubar1+fc0*fdbar1+2*fc0*fcbar1+fc0*fsbar1+fs0*fubar1+2*fs0*fdbar1+fs0*fcbar1+2*fs0*fsbar1+fubar0*fcbar1+2*fubar0*fsbar1+2*fdbar0*fcbar1+fdbar0*fsbar1;
  current_pdf_sum+=fu1*fc0+2*fu1*fs0+2*fu1*fubar0+fu1*fdbar0+2*fu1*fcbar0+fu1*fsbar0+2*fd1*fc0+fd1*fs0+fd1*fubar0+2*fd1*fdbar0+fd1*fcbar0+2*fd1*fsbar0+2*fc1*fubar0+fc1*fdbar0+2*fc1*fcbar0+fc1*fsbar0+fs1*fubar0+2*fs1*fdbar0+fs1*fcbar0+2*fs1*fsbar0+fubar1*fcbar0+2*fubar1*fsbar0+2*fdbar1*fcbar0+fdbar1*fsbar0;

  process_us_to_dcH.setMomenta(p_good);
  process_us_to_dcH.sigmaKin();
  current_ME2=process_us_to_dcH.getMatrixElements()[0];
  ME2+=current_pdf_sum*current_ME2;

  process_us_to_dcH.setMomenta(p_bad);
  process_us_to_dcH.sigmaKin();
  current_ME2=process_us_to_dcH.getMatrixElements()[0];
  ME2+=current_pdf_sum*current_ME2;

  return ME2;
}







double compute_ME_VBF_v3( cteqpdf ct10nn,
			  CPPProcess_ud_to_udH process_ud_to_udH,
			  vector<double*> p){

  //p0 incoming quark with eta>0
  //p1 incoming quark with eta<0
  //p2 outgoing quark with highest eta
  //p3 outgoing quark with lowest eta

  vector<double*> p_good=p;
  /*vector<double*> p_bad=p;
  p_bad[2]=p[3];
  p_bad[3]=p[2];*/
  
  double ME2=0;

  double E_proton=6500;
  double x0=p[0][0]/E_proton;
  double x1=p[1][0]/E_proton;
  double Q=125;

  double fu0=ct10nn.parton(2,x0,Q);
  double fd0=ct10nn.parton(1,x0,Q);
  double fc0=ct10nn.parton(4,x0,Q);
  double fs0=ct10nn.parton(3,x0,Q);
  double fubar0=ct10nn.parton(-2,x0,Q);
  double fdbar0=ct10nn.parton(-1,x0,Q);
  double fcbar0=ct10nn.parton(-4,x0,Q);
  double fsbar0=ct10nn.parton(-3,x0,Q);

  double fu1=ct10nn.parton(2,x1,Q);
  double fd1=ct10nn.parton(1,x1,Q);
  double fc1=ct10nn.parton(4,x1,Q);
  double fs1=ct10nn.parton(3,x1,Q);
  double fubar1=ct10nn.parton(-2,x1,Q);
  double fdbar1=ct10nn.parton(-1,x1,Q);
  double fcbar1=ct10nn.parton(-4,x1,Q);
  double fsbar1=ct10nn.parton(-3,x1,Q);

  double current_pdf_sum=0;
  double current_ME2=0;

  process_ud_to_udH.setMomenta(p_good);
  process_ud_to_udH.sigmaKin();
  current_ME2=process_ud_to_udH.getMatrixElements()[0];

  //uu->uuH, dd->ddH, cc->ccH, ss->ssH, ubarubar->ubarubarH, dbardbar->dbardbarH, cbarcbar->cbarcbarH, sbarsbar->sbarsbarH,
  current_pdf_sum=fu0*fu1+fd0*fd1+fc0*fc1+fs0*fs1+fubar0*fubar1+fdbar0*fdbar1+fcbar0*fcbar1+fsbar0*fsbar1;

  //ud->udH, cs->csH, ubardbar->ubardbarH, cbarsbar->cbarsbarH
  //Factor 2 because sizeable contribution from ud->udH + ud->duH
  current_pdf_sum+=2*(fu0*fd1+fc0*fs1+fubar0*fdbar1+fcbar0*fsbar1+fu1*fd0+fc1*fs0+fubar1*fdbar0+fcbar1*fsbar0);

  //Others: uc->ucH, us->usH, us->cdH, uubar->uubarH, uubar->ddbarH, udbar->udbarH, ucbar->ucbarH, ucbar->dsbarH, usbar->usbarH, dc->dcH, dc->usH, ds->dsH, dubar->dubarH, ddbar->ddbarH, ddbar->uubarH, dcbar->dcbarH, dsbar->dsbarH, dsbar->ucbarH, cubar->cubarH, cubar->sdbarH, cdbar->cdbarH, ccbar->ccbarH, ccbar->ssbarH, csbar->csbarH, subar->subarH, sdbar->sdbarH, sdbar->cubarH, scbar->scbarH, ssbar->ccbarH, ssbar->ssbarH, ubarcbar->ubarcbarH, ubarsbar->ubarsbarH, ubarsbar->cbardbarH, dbarcbar->dbarcbarH, dbarcbar->ubarsbarH, dbarsbar->dbarsbarH
  current_pdf_sum+=fu0*fc1+2*fu0*fs1+2*fu0*fubar1+fu0*fdbar1+2*fu0*fcbar1+fu0*fsbar1+2*fd0*fc1+fd0*fs1+fd0*fubar1+2*fd0*fdbar1+fd0*fcbar1+2*fd0*fsbar1+2*fc0*fubar1+fc0*fdbar1+2*fc0*fcbar1+fc0*fsbar1+fs0*fubar1+2*fs0*fdbar1+fs0*fcbar1+2*fs0*fsbar1+fubar0*fcbar1+2*fubar0*fsbar1+2*fdbar0*fcbar1+fdbar0*fsbar1;
  current_pdf_sum+=fu1*fc0+2*fu1*fs0+2*fu1*fubar0+fu1*fdbar0+2*fu1*fcbar0+fu1*fsbar0+2*fd1*fc0+fd1*fs0+fd1*fubar0+2*fd1*fdbar0+fd1*fcbar0+2*fd1*fsbar0+2*fc1*fubar0+fc1*fdbar0+2*fc1*fcbar0+fc1*fsbar0+fs1*fubar0+2*fs1*fdbar0+fs1*fcbar0+2*fs1*fsbar0+fubar1*fcbar0+2*fubar1*fsbar0+2*fdbar1*fcbar0+fdbar1*fsbar0;

  ME2=current_pdf_sum*current_ME2;

  return ME2;
}


#endif
